feat: 관리자의 상품 등록 요청에 대한 허가상태 변경, Product와 Brand 연결 후 코드 수정
teamGrowup/grow pull request #17
Opened 2024-08-14 05:41 UTC by JOWOONGHEE

## 변경사항
### AS-IS

### TO-BE

## 테스트
- [ ] 테스트 코드
- [ ] API 테스트

2024-08-14 06:15 UTC, taeGnues requested changes

2024-08-14 06:15 UTC, taeGnues commented on src/main/java/org/boot/growup/source/seller/controller/ProductController.java
> +    public BaseResponse<ProductDetailResponseDTO> readProductDetail(@PathVariable Long productId) {
저희 read api는 메소드명 get으로 하기로 했어서 수정해주셔야할 거 같아요1
getProductDetail로요!

2024-08-14 06:15 UTC, taeGnues commented on src/main/java/org/boot/growup/source/seller/persist/entity/Product.java
> +                .brand(Brand.builder().build())
이거는 brand가 null이 되지 않나요??? brand 엔티티를 패러미터로 넘겨주시는 게 좋을 것 같아요! 아니면 productRequestDto에 넣는 것도 좋을 것 같고 음 ..

지금 떠오르는 방식은 of(ProductRequestDTO productRequestDto, Brand brand) 로 해주시는 게 나을 것 같아요! 그리고 brand는 brandRepository에서 조회해서 가져오는 방식으로 짜야할 것 같아요!

2024-08-14 06:15 UTC, taeGnues commented on src/main/java/org/boot/growup/source/seller/persist/entity/Product.java
>                  .subCategory(SubCategory.builder().build())
이제 보긴했는데 SubCategory는 productRequestDto에서 가져와야할 것 같아요!

2024-08-14 06:15 UTC, taeGnues commented on src/main/java/org/boot/growup/source/seller/persist/repository/ProductRepository.java
> +
여기 들어간 공백들 없애줘야할 것 같아요!

2024-08-14 06:15 UTC, taeGnues commented on src/main/java/org/boot/growup/source/seller/service/ProductServiceImpl.java
> +        productRepository.save(product);
이거 여기 메소드에 @Transactional 걸어주시면 product.deny()만 하고 save는 굳이 안해주셔도 deny 상태로 변경돼요!!
jpa가 dirty checking을 해줘서 transactional 내부에서 entity의 변경이 생기면 자동으로 저장을 해줍니다!!

2024-08-14 10:40 UTC, Kim-Ji-Seop commented on src/main/java/org/boot/growup/source/seller/persist/repository/ProductRepository.java
> +    Optional<Product> findByIdAndSeller_Id(Long productId, Long sellerId);
Seller_Id 이렇게 해도 쿼리 잘 들어가나요?? 궁금해서요

2024-08-14 10:40 UTC, Kim-Ji-Seop commented on src/main/java/org/boot/growup/source/seller/service/ProductServiceImpl.java
>          );
만약 Seller가 상품 여러개를 등록해뒀다면 어떻게 되나요?

2024-08-14 10:40 UTC, Kim-Ji-Seop commented on src/main/java/org/boot/growup/source/seller/service/ProductServiceImpl.java
> +    @Transactional
@ Transactional
@ Override 
순서로 해주세요!

2024-08-15 03:48 UTC, JOWOONGHEE commented on src/main/java/org/boot/growup/source/seller/service/ProductServiceImpl.java
>          );
아 안그래도 이거때문에 상품업데이트가 잘 안되서 다른방식으로 하려고요

2024-08-15 04:49 UTC, Kim-Ji-Seop commented on src/main/java/org/boot/growup/source/seller/service/ProductServiceImpl.java
>          );
List로 받아와도 괜찮겠네요!

2024-08-15 04:56 UTC, JOWOONGHEE commented on src/main/java/org/boot/growup/source/seller/service/ProductServiceImpl.java
>          );
// 판매자ID와 상품 ID로 상품 조회
        Product product = productRepository.findByIdAndSeller_Id(productId, seller.getId())
        이렇게 하니 상품 업데이트 되네요

2024-08-15 11:10 UTC, merged